"""OpenAPI から Pydantic v2 モデルを生成するスクリプト（S-02 / api-contracts.md §3.2）。

`datamodel-code-generator` を使い、`shared/schema/openapi.yaml` から
`backend/src/common/models/api.py` を生成する。生成物は手動編集禁止。

実行:
    poetry run python scripts/gen_models.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OPENAPI = REPO_ROOT / "shared" / "schema" / "openapi.yaml"
OUTPUT = REPO_ROOT / "backend" / "src" / "common" / "models" / "api.py"


def main() -> int:
    """datamodel-codegen を呼び出して Pydantic モデルを生成する。"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "datamodel-codegen",
        "--input",
        str(OPENAPI),
        "--input-file-type",
        "openapi",
        "--output",
        str(OUTPUT),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.13",
        "--use-standard-collections",
        "--use-union-operator",
        "--custom-file-header",
        "# Generated by datamodel-codegen. Do not edit.",
    ]
    result = subprocess.run(cmd, check=False)  # noqa: S603
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
