/* Generated by openapi-typescript. Do not edit. */
/*
 * このファイルは `npm run schema:gen:ts`（openapi-typescript）で
 * shared/schema/openapi.yaml から生成される。手動編集禁止（api-contracts.md §3.1）。
 * CI で再生成し、コミット済みファイルと差分があれば fail する。
 *
 * 注: 下記は openapi.yaml の第1版骨格に対応する代表的な型のスナップショット。
 * 実際の生成では openapi-typescript が paths / components から完全な型を出力する。
 */

export interface components {
  schemas: {
    ProblemDetails: {
      /** @description エラーコードを URL 化したもの */
      type: string;
      /** @description 人間可読の要約（ユーザー表示可） */
      title: string;
      /** @description HTTP ステータスコード */
      status: number;
      /** @description 具体説明（PII / 内部情報は含めない） */
      detail?: string;
      /** @description 対象リソースのパス */
      instance?: string;
    };
    HealthStatus: {
      status: 'healthy' | 'degraded';
      checkedAt: string;
      dependencies?: { [key: string]: 'ok' | 'error' };
    };
    TelemetryValue: string | number | boolean;
    TelemetryEvent: {
      name: string;
      occurredAt: string;
      props?: { [key: string]: components['schemas']['TelemetryValue'] };
    };
    TelemetryEnvelope: {
      events: components['schemas']['TelemetryEvent'][];
      clientSentAt: string;
      schemaVersion: string;
    };
    IngestResult: {
      accepted: number;
      dropped: number;
    };
    User: {
      id: string;
      /** @description PII。ログ・テレメトリでは必ずマスク */
      email?: string;
      createdAt: string;
    };
    CalendarEvent: {
      category: 'presentation' | 'date' | 'camping' | 'other';
      timeRange: {
        startAt: string;
        endAt?: string;
      };
      confidence?: number;
    };
    UserProfile: {
      userId: string;
      monthlyDisposableYen?: number;
      monthlySavingsYen?: number;
      favoriteBrands?: string[];
      ngCategories?: string[];
      hasDebt?: boolean;
      associatesDisclosureAcknowledged?: boolean;
      onboardingStep?: number;
      profileCompleted?: boolean;
    };
    SafeguardSettings: {
      monthlyLimitYen: number;
      currentBudgetUsedYen?: number;
      remainingYen?: number;
      flags?: {
        cooldownOn?: boolean;
        quietWeek?: boolean;
        hasDebt?: boolean;
      };
      debtReleaseRequestedAt?: string | null;
    };
    Achievement: {
      exp: number;
      level: number;
      titles?: string[];
      currentStreakDays?: number;
    };
    HomeSnapshot: {
      candidateCount?: number;
      cartWatchCount?: number;
      yudaneLevel?: number;
      remainingBudgetYen?: number;
    };
  };
}

export type ProblemDetails = components['schemas']['ProblemDetails'];
export type HealthStatus = components['schemas']['HealthStatus'];
export type TelemetryEvent = components['schemas']['TelemetryEvent'];
export type TelemetryEnvelope = components['schemas']['TelemetryEnvelope'];
export type IngestResult = components['schemas']['IngestResult'];
export type User = components['schemas']['User'];
export type CalendarEvent = components['schemas']['CalendarEvent'];
export type UserProfile = components['schemas']['UserProfile'];
export type SafeguardSettings = components['schemas']['SafeguardSettings'];
export type Achievement = components['schemas']['Achievement'];
export type HomeSnapshot = components['schemas']['HomeSnapshot'];
