# Generated by datamodel-codegen. Do not edit.
#
# このファイルは `poetry run python scripts/gen_models.py`（datamodel-code-generator）で
# shared/schema/openapi.yaml から生成される。手動編集禁止（api-contracts.md §3.2）。
# CI で再生成し、コミット済みファイルと差分があれば fail する。
#
# 注: 下記は openapi.yaml の第1版骨格に対応する代表的なモデルのスナップショット。
from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class HealthStatusEnum(str, Enum):
    healthy = "healthy"
    degraded = "degraded"


class ProblemDetails(BaseModel):
    type: str
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None


class HealthStatus(BaseModel):
    status: HealthStatusEnum
    checkedAt: str
    dependencies: dict[str, str] | None = None


class TelemetryEvent(BaseModel):
    name: str
    occurredAt: str
    props: dict[str, str | float | bool] | None = None


class TelemetryEnvelope(BaseModel):
    events: list[TelemetryEvent] = Field(..., max_length=100)
    clientSentAt: str
    schemaVersion: str


class IngestResult(BaseModel):
    accepted: int
    dropped: int


class User(BaseModel):
    id: str
    email: str | None = None
    createdAt: str


class CalendarCategory(str, Enum):
    presentation = "presentation"
    date = "date"
    camping = "camping"
    other = "other"


class TimeRange(BaseModel):
    startAt: str
    endAt: str | None = None


class CalendarEvent(BaseModel):
    category: CalendarCategory
    timeRange: TimeRange
    confidence: float | None = None
